version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install m4 -y
      - run: opam install --deps-only .
      - run: dune build bin/tiger.exe