version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2
    steps:
      - checkout
      - run: apt-get install m4
      - run: opam install --deps-only .
      - run: dune build bin/tiger.exe