version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install m4 -y
      - run: opam install --deps-only .
      - run:
          name: Build the executable
          command: |
            eval $(opam env)
            dune build bin/tiger.exe
      - run:
          name: Test
          command: |
            eval $(opam env)
            dune runtest