[package]
name = "parser"
version = "0.1.0"
authors = ["amlo <xplzjwz@gmail.com>"]
edition = "2018"

[profile.dev.package.parsergens]
opt-level = 2

[dependencies]
parsergens = { git = "https://github.com/arucil/parsergens" }
